### ISSUE TITLE
Changes to _config.yml do not trigger auto-regeneration

### ISSUE THREAD

**Issue by tetrapharmakon** [paolobrasolin/jekyll-antex#8] opened 2018-05-09 10:11 UTC
Changing

```
antex:
  preamble:
    [...]
     \def\V{\mathcal{V}}
```
into

```
antex:
  preamble:
    [...]
    \def\V{\mathbf{V}}
```
*.tex files in .antex-cache/ do not see the modification.

**Comment by paolobrasolin** [comment] 2018-09-04 16:39
Changes to `_config.yml` are not watched by Jekyll: this is expected behaviour as stated in jekyll/jekyll#2302. That makes sense to me too, so I'm not going to work around that.

However that leaves us without a place to define a dynamically reloaded preamble with a scope wider than a single page, and having that _also_ makes sense to me.

A possibility would be to put yout `antex` configuration in the front matter of layouts; then it would be dynamically reloaded and you could either keep in your default layout, or in an ad hoc one, or in any number of different layouts to be used in different parts of your site.

I'm currently ignoring the front matters of layouts, so a (trivial) fix is needed.

Would that do, @tetrapharmakon?

**Comment by paolobrasolin** [comment] 2018-09-12 21:08
@tetrapharmakon closing this, as it's not a bug but expected behaviour.
If we come to some conclusion about layouts we'll open a new feature request.

**Closed by paolobrasolin** 2018-09-12 21:08 UTC
Labels: invalid
